server:
  port: 8095

spring:
  liquibase:
    enabled: true

#    default-schema: custom_pizza

  #  datasource:
#    url: jdbc:postgresql://localhost:5432/custompizza?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectionCollation=utf8_general_ci&amp;characterSetResults=UTF-8
#    username: postgres
#    password: root1289User
#    driver-class-name: org.postgresql.Driver
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
#          show_sql: true
#    properties:
#      hibernate:
#        show_sql: false
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
#        temp:
#          use_jdbc_metadata_defaults: false
#        jdbc:
#          lob: non_contextual_creation=true

#      generate-ddl: false
#      show-sql: true
#      open-in-view: false


  datasource:
    #url: jdbc:h2:mem:custom_pizza;
    url: jdbc:h2:file:./db;INIT=CREATE SCHEMA IF NOT EXISTS custom_pizza
    username: u
    password:
    driverClassName: org.h2.Driver

#    generate-unique-name: false
#    name: custom_pizza

logging:
  file:
    name: logs/app_dev.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  level:
    org:
      springframework:
        web: ERROR
    com:
      sshibko:
        custompizza: DEBUG